package clearcontrol.devices.cameras;

import clearcontrol.core.device.openclose.OpenCloseDeviceInterface;
import clearcontrol.core.device.openclose.ReOpenDeviceInterface;
import clearcontrol.core.device.startstop.StartStopDeviceInterface;
import clearcontrol.core.variable.Variable;

/**
 * Interface implemented by all cameras.
 *
 * @author royer
 */
public interface CameraDeviceInterface extends
                                       OpenCloseDeviceInterface,
                                       StartStopDeviceInterface,
                                       ReOpenDeviceInterface
{

  /**
   * Convenience method for setting the exposure time in microseconds
   * 
   * @param pExposureInMicroseconds
   *          exposure in microseconds
   */
  void setExposure(double pExposureInMicroseconds);

  /**
   * Convenience method that returns the exposure in microseconds.
   * 
   * @return exposure in microseconds
   */
  double getExposure();

  /**
   * This is a convenience method that can (software) trigger the camera.
   */
  void trigger();

  /**
   * Returns the variable holding the current acquisition index.
   * 
   * @return acquisition index variable
   */
  Variable<Long> getCurrentIndexVariable();

  /**
   * Returns the variable holding the line readout time in microseconds
   * 
   * @return line readout time variable
   */
  Variable<Double> getLineReadOutTimeInMicrosecondsVariable();

  /**
   * Returns the variable holding the exposure time in microseconds
   * 
   * @return exposure time variable
   */
  Variable<Double> getExposureInMicrosecondsVariable();

  /**
   * Returns the variable holding the pixel size in nanometers
   * 
   * @return pixel size in nanometer variable
   */
  Variable<Double> getPixelSizeInNanometersVariable();

  /**
   * Returns variable holding the boolean flag indicating whether the camera is
   * currently acquiring
   * 
   * @return acquiring flag variable
   */
  Variable<Boolean> getIsAcquiringVariable();

  /**
   * Returns the variable holding the current channel. Channels can be set on
   * the camera so that the stacks generated by the camera can be already
   * assigned a channel.
   * 
   * @return current channel variable
   */
  Variable<Integer> getChannelVariable();

  /**
   * Returns the variable holding the trigger signal. Sending an edge (false
   * then true) triggers the camera (single image)
   * 
   * @return trigger variable
   */
  Variable<Boolean> getTriggerVariable();

}
